version: '3.8'

services:
  llm-tuning:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-tuning-dev
    volumes:
      - .:/workspace
      - pipenv-cache:/root/.local/share/virtualenvs
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    environment:
      - PIPENV_VENV_IN_PROJECT=1

volumes:
  pipenv-cache:
